# Generated by Django 6.0.4 on 2026-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_publisher_id_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishervideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pub_videos/'),
        ),
        migrations.AlterField(
            model_name='publishervideo',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
