# Generated by Django 6.0.4 on 2026-05-01 02:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publishervideo_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishervideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
