# Generated by Django 6.0.4 on 2026-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_publishervideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publishervideo',
            name='thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
    ]
